### ISSUE TITLE
http://127.0.0.1:8080/h264/h264.html

### ISSUE THREAD

**Issue by ctlyh3059** [wangdxh/websocketvideostream#2]
new socket
2017/10/08 21:23:25 16777216
2017/10/08 21:23:25 http: panic serving 127.0.0.1:23742: runtime error: slice bounds out of range
goroutine 32 [running]:
net/http.(*conn).serve.func1(0x12827e60)
	c:/go/src/net/http/server.go:1697 +0x9f
panic(0x5eb220, 0x74d3a8)
	c:/go/src/runtime/panic.go:491 +0x1d0
main.wsH264(0x126602d0)
	G:/jsh264/websocketvideostream/main.go:43 +0x549
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	c:/go/src/golang.org/x/net/websocket/server.go:89 +0x128
golang.org/x/net/websocket.Handler.ServeHTTP(0x6316e4, 0x723ea0, 0x1281ecf0, 0x1264ab80)
	c:/go/src/golang.org/x/net/websocket/server.go:112 +0x5a
net/http.(*ServeMux).ServeHTTP(0x752780, 0x723ea0, 0x1281ecf0, 0x1264ab80)
	c:/go/src/net/http/server.go:2254 +0xf0
net/http.serverHandler.ServeHTTP(0x125f8180, 0x723ea0, 0x1281ecf0, 0x1264ab80)
	c:/go/src/net/http/server.go:2619 +0x8e
net/http.(*conn).serve(0x12827e60, 0x724400, 0x1294d5c0)
	c:/go/src/net/http/server.go:1801 +0x5d1
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:2720 +0x1f6
send over socket

can you give me h264  test file?

**Comment by wangdxh** [comment]
here i use boost rewrite the stream server， 

in  http://www.jianshu.com/p/12b41f105836    there are github link and chinese comment
